# Generated by Django 4.0.5 on 2022-07-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'diagnoses',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'symptoms',
            },
        ),
        migrations.CreateModel(
            name='FocalElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('bpa', models.DecimalField(decimal_places=3, max_digits=4)),
                ('symptoms', models.ManyToManyField(related_name='focal_elements', to='dempster_shafer_structure.symptom')),
            ],
            options={
                'db_table': 'focal_elements',
            },
        ),
    ]
