# Generated by Django 4.0.5 on 2022-07-06 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dempster_shafer_structure', '0002_symptom_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocalElementSymptomWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('focal_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_weights', to='dempster_shafer_structure.focalelement')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focal_element_weights', to='dempster_shafer_structure.symptom')),
            ],
        ),
    ]
