# Generated by Django 4.0.5 on 2022-07-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempster_shafer_structure', '0003_focalelementsymptomweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focalelement',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
