# Generated by Django 4.0.5 on 2022-06-30 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utility_matrix', '0002_utilitymatrixdata_utility_collections_matrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregation_type', models.CharField(choices=[('weighted_average', 'Weighted Average'), ('ordered_weighted_average', 'Ordered Weighted Average'), ('choquet_integral', 'Choquet Integral'), ('discrimination_analysis', 'Discrimination Analysis')], max_length=64)),
                ('aggregated_data_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utility_matrix_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregations', to='utility_matrix.utilitymatrixdata')),
            ],
            options={
                'db_table': 'aggregations',
            },
        ),
    ]
