# Generated by Django 4.0.5 on 2022-07-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregation',
            name='aggregation_type',
            field=models.CharField(choices=[('weighted_average', 'Weighted Average'), ('ordered_weighted_average', 'Ordered Weighted Average'), ('dempster_extreme_expectations', 'Dempster Extreme Expectations'), ('choquet_integral', 'Choquet Integral'), ('discrimination_analysis', 'Discrimination Analysis')], max_length=64),
        ),
    ]
