# Generated by Django 4.0.5 on 2022-06-30 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityMatrixData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_raw_data_json', models.JSONField()),
                ('discrimination_qrang_matrix_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='utility_matrices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'utility_matrix_data',
            },
        ),
    ]
